apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1
  labels:
    app: frontend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-1
  template:
    metadata:
      labels:
        app: frontend-1
    spec:
      containers:
      - name: frontend
        image: dockertanj/frontend
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
